### ISSUE TITLE
An unexpected error occurred , from resource to public page dr25

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#10]
![image](https://github.com/inbo/vlaams-biodiversiteitsportaal/assets/3965195/f6cf8033-75df-4455-9676-cdaefcc05087)

When browsing from https://collections.biodiversiteitsportaal.dev.svdev.be/dataResource/show/dr25 -->  tohttps://collections.biodiversiteitsportaal.dev.svdev.be/public/show/dr25 an unexpected error occured

*Error 500: Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/public/showDataResource.gsp:386] Error executing tag <g:render>: [views/public/_charts.gsp:84] Error executing tag <asset:script>: [views/public/_charts.gsp:83] Error executing tag <charts:biocache>: /data/collectory/config/charts.json (No such file or directory)
Servlet: grailsDispatcherServlet
URI: /public/show/dr25
Exception Message: Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/public/showDataResource.gsp:386] Error executing tag <g:render>: [views/public/_charts.gsp:84] Error executing tag <asset:script>: [views/public/_charts.gsp:83] Error executing tag <charts:biocache>: /data/collectory/config/charts.json (No such file or directory)
Caused by: Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/public/showDataResource.gsp:386] Error executing tag <g:render>: [views/public/_charts.gsp:84] Error executing tag <asset:script>: [views/public/_charts.gsp:83] Error executing tag <charts:biocache>: /data/collectory/config/charts.json (No such file or directory)
Class: gsp_collectory_publicshowDataResource_gsp.groovy
At Line: [610]*

**Comment by StefanVanDyck** [comment]
Is gefixed, er blijken nog een aantal "hard-coded" paden te zijn.
Of ten minsten, paden die niet eenvoudig aan te passens zijn via config aanpassingen.
(Tijdelijke-)Oplossing: de files copieren naar de verwachte locatie voor het starten van de containers
