### ISSUE TITLE
Search for records in Vlaams Biodiversiteitsportaal

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#13]
When "Search for records in Vlaams Biodiversiteitsportaal"
The the map gives the map of Northern Africa by defout. This also shoul be Flanders.

![image](https://github.com/inbo/vlaams-biodiversiteitsportaal/assets/3965195/603ed454-60b8-4075-97e8-690f86d4324d)

**Comment by StefanVanDyck** [comment]
Is fixed, was a config value in ala-hub module
