### ISSUE TITLE
CORS errors from the branding server are causing fonts and images not to be downloaded on the ALA components

### ISSUE THREAD

**Issue by stenmigerode** [inbo/vlaams-biodiversiteitsportaal#2]
A hard refresh fixes this problem.

To be debugged to find the root cause.

**Comment by stenmigerode** [comment]
- [ ] Debug the HTTP requests to see why the right allowed origin is not returned by the branding server
- [ ] Find a fix if the root cause is found

**Comment by StefanVanDyck** [comment]
https://github.com/AtlasOfLivingAustralia/ala-install/pull/799

Seems like the root cause was caching of CORS response by the browser.
Submitted a fix to the ala-install repo
