### ISSUE TITLE
Map collection homepage not visible

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#20]
On https://collections.biodiversiteitsportaal.dev.svdev.be/?lang=nl the map is not visible.
Browser: Google chroome/ firefox/ edge

![image](https://github.com/inbo/vlaams-biodiversiteitsportaal/assets/3965195/a58156c6-379e-4927-967c-33d79c65b44c)

**Comment by StefanVanDyck** [comment]
Required a mapbox api key in order to work.
