### ISSUE TITLE
list records in regions

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#24]
![image](https://github.com/inbo/vlaams-biodiversiteitsportaal/assets/3965195/42e69cd5-d927-48cf-aece-efea044570da)

List records click in regions creates an error.

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>DK2729T03MGV4MPN</RequestId>
<HostId>G9JAlibJKt+k++BLpMHIEktfnfUMvfZhabwSo2C1/VErXvSjld+mMHNGmV2KWMnmAvKjIsNF6lg=</HostId>
`</Error>`

**Comment by StefanVanDyck** [comment]
Incorrect git commit message.
Fixed by https://github.com/inbo/vlaams-biodiversiteitsportaal/commit/93e4719d9c5afae45835962618fc21da4645451f
