### ISSUE TITLE
In Regions: Time controls and map creates an error

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#26]
When clicking time control and map, an error was created

url: https://regions.biodiversiteitsportaal.dev.svdev.be/Gemeenten/Kalmthout?pid=1169#group=ALL_SPECIES&subgroup=&guid=&from=1930&to=1940&tab=speciesTab&fq=

![image](https://github.com/inbo/vlaams-biodiversiteitsportaal/assets/3965195/a9c53044-11fe-4156-8c14-e99b77eb2304)

**Comment by StefanVanDyck** [comment]
Cause by not properly encoding query url, opened a PR to have fix added upstream
