### ISSUE TITLE
list error

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#55]
Something fails when uploading a list

https://lists.biodiversiteitsportaal.dev.svdev.be/speciesList/upload

![image](https://github.com/user-attachments/assets/d872cbbb-cafd-4eea-9c0c-4fbbf8413fc0)
![image](https://github.com/user-attachments/assets/78bdf13a-5fc5-44ae-89ce-e4e44e4e19be)

**Comment by StefanVanDyck** [comment]
Request to namematching service was timing out.
Caused by missing security group rule to allow communication.

**Comment by StefanVanDyck** [comment]
@DimEvil Could you test again? :bow:

**Comment by DimEvil** [comment]
![image](https://github.com/user-attachments/assets/a53a4932-0d50-4be8-b640-a9afaaf148d1)
 error!

**Comment by DimEvil** [comment]
The same 'test list' list works in the ALA
