### ISSUE TITLE
unable to delete lists

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#65]
url: https://lists.biodiversiteitsportaal.dev.svdev.be/admin/speciesLists

Click on Delete results in following error

![image](https://github.com/user-attachments/assets/15fa0478-8902-4896-893d-bc6871b3523a)

Click to view list provides following error

url: https://lists.biodiversiteitsportaal.dev.svdev.be/speciesListItem/list/drt1720007227225

![image](https://github.com/user-attachments/assets/0ee40b9b-6af9-41ef-8cd2-f993cb813bf0)

**Comment by StefanVanDyck** [comment]
Fixed it by preventing addition of foreing key constraint, should probably create a PR with an actual proper fix that does make sure a foreign key constraint is created correctly.
