### ISSUE TITLE
Dataset to be added

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#7]
Datasets to be added

- [x] dr41
- [x] dr80
- [x] dr93

- [ ] 18
- [ ] 32
- [ ] 37
- [ ] 29
- [ ] 35

- [ ] 12
- [x] 11

This should give a nice overview of data from Flanders

**Comment by stenmigerode** [comment]
Ivm indexatie:
Al onze Data Resources hebben een verkeerde instelling: 
![afbeelding](https://user-images.githubusercontent.com/27133403/197148838-f21bb247-ee07-4184-a4f3-08fac1a6a68f.png)

Na deze aanpassing kunnen we ze pas inladen: eventueel een **force-load** als we de verkeerde al eens hadden ingeladen.

```
bash> sudo biocache
...
biocache> load dr80
...
biocache> process -dr dr80
...
biocache> sample -dr dr80
...
biocache> index -dr dr80
```

**Comment by stenmigerode** [comment]
Geen idee of dat een bug is, of dat verkeerd in onze datasets zit, of dat het normaal is dat we deze aanpassing in ala admin doen voor we de indexatie starten

**Comment by DimEvil** [comment]
Dit zit denk ik verkeerd in de atlas. Bij ons is dat occurrenceID , we
hebben dat ook moeten aanpassen bij die eerste dataset. Flora2.



Op vr 21 okt. 2022 11:25 schreef Sten Migerode ***@***.***>:

**Comment by StefanVanDyck** [comment]
In gestions of all datasets seems possible (just a matter of time, especially for big ones like flora and waarnemingen).
Closing this as we will have to do a new excercise to determine which datasets to include, etc.
