### ISSUE TITLE
error when adding layers

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#80]
url: https://spatial.biodiversiteitsportaal.dev.svdev.be/ws/manageLayers/layers?layer_id=1723551744569&error=error+creating+layer%3A+could+not+execute+statement%3B+SQL+%5Bn%2Fa%5D%3B+nested+exception+is+org.hibernate.exception.DataException%3A+could+not+execute+statement

An error (in url) was given when trying to add IFBL layer in the spatial portal.

For some layers, i.e. "agrarisch gebied" no error was given

**Comment by DimEvil** [comment]
If I change the bounding box of the layers in the geoserver to +90 -90 , +180 - 180 , in many case it will run.
A wild guess is that the bounding box of the new layer is not in Australia (= original value), when making it a global bounding box it will also cover Australia and therefore considered correct.

**Comment by StefanVanDyck** [comment]
Cause by a numeric overflow when using a language with a different decimal operator:
https://github.com/AtlasOfLivingAustralia/spatial-service/issues/247

Workaround is to always use the English language when saving layers.

Trying to figure out a proper fix, but might be tricky, considering the mess of magical things happening.
