### ISSUE TITLE
error gives on species

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#87]
url: https://species.biodiversiteitsportaal.dev.svdev.be/species/urn:lsid:catalogueoflife.org:taxon:d1d7b267-2dc5-11e0-98c6-2ce70255a436:col20120124

results in an error.

strange that this is still CoL (Catalogue of life)

**Comment by DimEvil** [comment]
same error with all species, it seems

**Comment by DimEvil** [comment]
also: https://species.biodiversiteitsportaal.dev.svdev.be/species/5229490 (pica pica) was not found

**Comment by DimEvil** [comment]
although some are working: https://species.biodiversiteitsportaal.dev.svdev.be/species/729

**Comment by StefanVanDyck** [comment]
Fixed with new index
