### ISSUE TITLE
Damiano Oldoni rules the contacts in the VBP

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#89]
Damiano Oldoni is almost primary (and other contact) for most datasets. This is not correct.
Also they are not 100% correct imported I guess.

![image](https://github.com/user-attachments/assets/fc04b3ac-7234-4794-b6a6-e7e64e11157e)

![image](https://github.com/user-attachments/assets/c1885485-241a-49a2-a2f7-6a64553c82ab)

**Comment by StefanVanDyck** [comment]
manually delete Damiano from contacts.
See if the problem re-occurs next time we sync
