### ISSUE TITLE
Number of records doubled

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#90]
check:  https://collections.biodiversiteitsportaal.dev.svdev.be/public/showDataResource/dr426 n° records: 16106
check: https://www.gbif.org/dataset/ea64939f-0dd1-4f6a-9f16-bd6c37b6c2e5 (original dataset) n° records:  8053

Was this dataset imported twice? 

https://records.biodiversiteitsportaal.dev.svdev.be/occurrences/686b419a-1a0d-41af-bfbc-23051ae95ae1
https://records.biodiversiteitsportaal.dev.svdev.be/occurrences/77f091a5-f131-4451-88fc-300044b7205e

These are the same records.

There is no check (apparently) on double unique occurrenceID's

guess: imported twice, one time through pipelines (GBIF) and one time through INBO IPT ?

!!This is not the case for all datasets!!
https://collections.biodiversiteitsportaal.dev.svdev.be/public/showDataResource/dr440  n° records: 20 080
https://www.gbif.org/dataset/53b55f0b-eace-46da-b414-351f092e1223  n° of records 20 080

This one is fine for example

**Comment by DimEvil** [comment]
https://collections.biodiversiteitsportaal.dev.svdev.be/public/showDataResource/dr425  n° records: 6236
https://www.gbif.org/dataset/bced6c7a-c7e0-40f7-b009-5f0478104716 n° records: 3118

**Comment by StefanVanDyck** [comment]
Probably caused by switching taxon backbones etc.
Normally reprocessing should not cause occurences to be loaded twice.

Assuming that by switching taxons, the occurences no longer matched and were not flagged as duplicates.
