### ISSUE TITLE
import data providers button is not working

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#91]
button: import from GBIF is not working (it did before, if I remember correctly).

https://collections.biodiversiteitsportaal.dev.svdev.be/dataProvider/list

![image](https://github.com/user-attachments/assets/7985ca04-7d7d-4215-a16e-660fde32fec9)

**Comment by StefanVanDyck** [comment]
Was using old credentials to gbif API.
Updating secret made it work

**Comment by StefanVanDyck** [comment]
Also had a mismatch in references env var <> java properties
