### ISSUE TITLE
Adding species based on lifeform does not work correctly

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#97]
If I choose lifeform in the spatial portal, no option for planst, or fungi

https://spatial.biodiversiteitsportaal.dev.svdev.be/

![image](https://github.com/user-attachments/assets/bd329f48-ed08-4ec1-af44-ad180e87f608)

**Comment by StefanVanDyck** [comment]
With the latest indexation we have a lot more options, including "Plants".
Unfortunately, when we choose Plant it does not find any occurence.
When choosing Plantae, it does work...

**Comment by DimEvil** [comment]
Closing issue for the moment, util taxonomy changes again....
