### ISSUE TITLE
error in search

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#98]
When searching for a scientific name (for example Epidalea calamita 'rugstreeppad') in the main search an error is generated.

https://species.biodiversiteitsportaal.dev.svdev.be/search?q=Epidalea+calamita

![image](https://github.com/user-attachments/assets/07ec8f86-c729-4a55-9857-a6539bef58a5)

When searching for the same species, but with the Dutch name 'rugstreeppad' an answer was given

![image](https://github.com/user-attachments/assets/2d987a04-8812-4e41-a5ae-ee59c940d73c)

Where we see 2 answers, going to the acceptedName and a synonym

Wild guess is that when in the search, the name is already suggested, the search is not working

![image](https://github.com/user-attachments/assets/5699855d-df5d-4369-a625-afb50189a66e)

**Comment by StefanVanDyck** [comment]
Is working at the moment.
Probably due to the biocache-service not working correctly due to [depedency on cassandra service](https://github.com/inbo/vlaams-biodiversiteitsportaal/issues/99).
